#! /bin/sh
# /etc/init.d/radiodan

### BEGIN INIT INFO
# Provides:          radiodan
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       A simple script from www.stuffaboutcode.com which will start / stop a program a boot / shutdown.
### END INIT INFO

#USERNAME=pi

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting radiodan"
    # run application you want to start
    cd /home/pi/radiodan_example; ./bin/start  > /home/pi/radiodan_example/log.txt 2>&1
    ;;
  stop)
    echo "Stopping radiodan"
    # kill application you want to stop
    sudo pkill -f bin/start
    ;;
  *)
    echo "Usage: /etc/init.d/radiodan {start|stop}"
    exit 1
    ;;
esac

exit 0
